#!/usr/bin/env python3

import argparse
import copy
import hashlib
import json
import os
import re
import stat
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
RESEARCH_ROOT = ROOT / "research"
BASE_SHA = "5eeeba7df24d32423c3867cb778c5d64bb8bfde3"
AUDIT_SOURCE_HEAD_SHA = "a624290be14ce495200ba96fd746c2d82ecd6ec6"
TARGET = "Sources/MLXFastModel/LagunaRuntimeModel.swift"
PRIOR_MANIFEST = "research/ranked-best-payload-gap-audit.json"
EXPECTED_CONTRACT_SHA256 = (
    "e01d3ea1c9281cfe81e1693d987627005fed6963440fbef6a761e4f28dd67fb6"
)
EXPECTED_CANONICAL_MANIFEST_SHA256 = (
    "2622b4de40b12f19fb696755425819b3c5faf7dfc300ac9d2ca7f9e2f9575230"
)
EXPECTED_FILE_COUNT = 142
EXPECTED_TOTAL_BYTES = 2_984_121
EXPECTED_GLOBAL_HEADROOM = 15_879
EXPECTED_TARGET_BYTES = 511_690
EXPECTED_TARGET_HEADROOM = 12_598
MAX_TOTAL_BYTES = 3_000_000
MAX_FILE_BYTES = 524_288
GLOBAL_RECLAMATION_GATE = 16_384
TARGET_RECLAMATION_GATE = 8_192

LICENSE_OR_TOOLING_MARKERS = (
    b"copyright",
    b"spdx-license",
    b"licensed under",
    b"license agreement",
    b"all rights reserved",
    b"do not edit",
    b"generated by",
    b"swiftlint:",
    b"swift-format",
    b"sourcery:",
    b"sourcekit:",
)
SOURCE_LOCATION_PATTERN = re.compile(
    rb"#(?:line|column|sourceLocation)\b"
)


class AuditError(RuntimeError):
    pass


@dataclass(frozen=True)
class Span:
    kind: str
    start: int
    end: int
    hashes: int = 0
    multiline: bool = False


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def git_bytes(*args: str) -> bytes:
    process = subprocess.run(
        ["git", *args],
        cwd=ROOT,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if process.returncode != 0:
        message = process.stderr.decode("utf-8", errors="replace").strip()
        raise AuditError(f"git {' '.join(args)} failed: {message}")
    return process.stdout


def validate_relative_path(value: str) -> None:
    path = Path(value)
    if (
        not value
        or path.is_absolute()
        or "\\" in value
        or "\x00" in value
        or any(part in ("", ".", "..") for part in path.parts)
    ):
        raise AuditError(f"unsafe editable path: {value!r}")


def base_contract() -> tuple[dict[str, Any], bytes]:
    raw = git_bytes("show", f"{BASE_SHA}:benchmark.json")
    if sha256(raw) != EXPECTED_CONTRACT_SHA256:
        raise AuditError("required-base benchmark.json hash drifted")
    current = (ROOT / "benchmark.json").read_bytes()
    if current != raw:
        raise AuditError("working benchmark.json differs from the required base")
    contract = json.loads(raw)
    rules = contract.get("editablePaths")
    if not isinstance(rules, list) or not rules:
        raise AuditError("required-base benchmark.json has no editablePaths")
    for rule in rules:
        if not isinstance(rule, str):
            raise AuditError("editablePaths includes a non-string entry")
        validate_relative_path(rule)
    return contract, raw


def base_surface_paths(rules: list[str]) -> list[str]:
    paths: set[str] = set()
    for rule in rules:
        raw = git_bytes("ls-tree", "-r", "--name-only", "-z", BASE_SHA, "--", rule)
        for item in raw.split(b"\0"):
            if not item:
                continue
            path = item.decode("utf-8")
            validate_relative_path(path)
            paths.add(path)
    return sorted(paths)


def working_surface_paths(rules: list[str]) -> tuple[list[str], dict[str, str]]:
    paths: set[str] = set()
    matched_by: dict[str, str] = {}
    for rule in rules:
        absolute = ROOT / rule
        if absolute.is_symlink():
            raise AuditError(f"editable path is a symlink: {rule}")
        if absolute.is_file():
            candidates = [absolute]
        elif absolute.is_dir():
            candidates = [path for path in absolute.rglob("*") if path.is_file()]
        else:
            candidates = []
        for absolute_path in candidates:
            mode = absolute_path.lstat().st_mode
            if stat.S_ISLNK(mode) or not stat.S_ISREG(mode):
                raise AuditError(f"non-regular submitted path: {absolute_path}")
            relative = absolute_path.relative_to(ROOT).as_posix()
            if relative in paths and matched_by[relative] != rule:
                raise AuditError(
                    f"submitted path matched multiple rules: {relative}"
                )
            paths.add(relative)
            matched_by[relative] = rule
    return sorted(paths), matched_by


def scan_swift(data: bytes) -> list[Span]:
    spans: list[Span] = []
    length = len(data)
    index = 0
    while index < length:
        if data.startswith(b"//", index):
            end = data.find(b"\n", index + 2)
            if end < 0:
                end = length
            spans.append(Span("line_comment", index, end))
            index = end
            continue
        if data.startswith(b"/*", index):
            start = index
            index += 2
            depth = 1
            while index < length and depth:
                if data.startswith(b"/*", index):
                    depth += 1
                    index += 2
                elif data.startswith(b"*/", index):
                    depth -= 1
                    index += 2
                else:
                    index += 1
            if depth:
                raise AuditError("unterminated nested Swift block comment")
            spans.append(Span("block_comment", start, index))
            continue

        hashes = 0
        quote_index = index
        if data[index] == 0x23:
            while quote_index < length and data[quote_index] == 0x23:
                hashes += 1
                quote_index += 1
        if quote_index < length and data[quote_index] == 0x22:
            multiline = data.startswith(b'"""', quote_index)
            quote_length = 3 if multiline else 1
            opening_start = index if hashes else quote_index
            body = quote_index + quote_length
            closing = b'"' * quote_length + b"#" * hashes
            cursor = body
            while cursor < length:
                if data.startswith(closing, cursor):
                    end = cursor + len(closing)
                    spans.append(
                        Span(
                            "string",
                            opening_start,
                            end,
                            hashes=hashes,
                            multiline=multiline,
                        )
                    )
                    index = end
                    break
                if hashes == 0 and data[cursor] == 0x5C:
                    cursor += 2
                    continue
                if not multiline and data[cursor] in (0x0A, 0x0D):
                    raise AuditError("newline in a single-line Swift string")
                cursor += 1
            else:
                raise AuditError("unterminated Swift string")
            continue
        index += 1
    return spans


def line_number(data: bytes, offset: int) -> int:
    return data.count(b"\n", 0, offset) + 1


def masked_code(data: bytes, spans: list[Span]) -> bytes:
    masked = bytearray(data)
    for span in spans:
        for index in range(span.start, span.end):
            if masked[index] not in (0x0A, 0x0D):
                masked[index] = 0x20
    return bytes(masked)


def whole_line_comment_blocks(
    data: bytes, spans: list[Span]
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    candidates: list[dict[str, Any]] = []
    exclusions: list[dict[str, Any]] = []
    whole_lines: list[tuple[Span, int, int, int]] = []
    for span in spans:
        if span.kind != "line_comment":
            continue
        start = data.rfind(b"\n", 0, span.start) + 1
        prefix = data[start:span.start]
        if prefix.strip(b" \t"):
            exclusions.append(
                {
                    "line": line_number(data, span.start),
                    "reason": "trailing_or_inline_comment",
                }
            )
            continue
        end = span.end
        if end > start and data[end - 1 : end] == b"\r":
            end -= 1
        if end <= start:
            continue
        whole_lines.append((span, start, end, line_number(data, start)))

    blocked_lines: set[int] = set()
    block: list[tuple[Span, int, int, int]] = []
    blocks: list[list[tuple[Span, int, int, int]]] = []
    for item in whole_lines:
        if block and item[3] != block[-1][3] + 1:
            blocks.append(block)
            block = []
        block.append(item)
    if block:
        blocks.append(block)

    for comment_block in blocks:
        combined = b"\n".join(
            data[item[0].start : item[0].end].lower() for item in comment_block
        )
        markers = [
            marker.decode("ascii")
            for marker in LICENSE_OR_TOOLING_MARKERS
            if marker in combined
        ]
        if markers:
            for item in comment_block:
                blocked_lines.add(item[3])
            exclusions.append(
                {
                    "start_line": comment_block[0][3],
                    "end_line": comment_block[-1][3],
                    "reason": "required_license_or_tooling_directive_block",
                    "markers": markers,
                }
            )

    for _span, start, end, line in whole_lines:
        if line in blocked_lines:
            continue
        removed = data[start:end]
        candidates.append(
            {
                "start_byte": start,
                "end_byte_exclusive": end,
                "start_line": line,
                "end_line": line,
                "class": "swift_whole_line_comment_body_preserve_newline",
                "bytes": len(removed),
                "removed_sha256": sha256(removed),
                "proof_id": "swift-comment-token-preserve-line-map-v1",
            }
        )
    return candidates, exclusions


def apply_ranges(data: bytes, ranges: list[dict[str, Any]]) -> bytes:
    output: list[bytes] = []
    cursor = 0
    for item in ranges:
        start = item["start_byte"]
        end = item["end_byte_exclusive"]
        if not (cursor <= start < end <= len(data)):
            raise AuditError("range ordering or bounds failure")
        removed = data[start:end]
        if len(removed) != item["bytes"]:
            raise AuditError("range byte count mismatch")
        if sha256(removed) != item["removed_sha256"]:
            raise AuditError("range removed-byte hash mismatch")
        output.append(data[cursor:start])
        cursor = end
    output.append(data[cursor:])
    return b"".join(output)


def reconstruct_original(
    candidate: bytes, ranges: list[dict[str, Any]], removed: list[bytes], original_size: int
) -> bytes:
    output: list[bytes] = []
    original_cursor = 0
    candidate_cursor = 0
    for item, deleted in zip(ranges, removed, strict=True):
        gap_length = item["start_byte"] - original_cursor
        output.append(candidate[candidate_cursor : candidate_cursor + gap_length])
        candidate_cursor += gap_length
        output.append(deleted)
        original_cursor = item["end_byte_exclusive"]
    tail_length = original_size - original_cursor
    output.append(candidate[candidate_cursor : candidate_cursor + tail_length])
    candidate_cursor += tail_length
    if candidate_cursor != len(candidate):
        raise AuditError("reverse reconstruction did not consume candidate")
    return b"".join(output)


def language_for(path: str) -> str:
    suffix = Path(path).suffix
    return {
        ".swift": "swift",
        ".cpp": "c++",
        ".h": "c++/metal-header",
        ".metal": "metal",
    }.get(suffix, "unknown")


def swift_contains_embedded_source(data: bytes) -> bool:
    spans = scan_swift(data)
    markers = (b"threadgroup_position_in_grid", b"metal::", b"kernel void")
    return any(
        span.kind == "string"
        and any(marker in data[span.start : span.end] for marker in markers)
        for span in spans
    )


def source_classification(path: str, data: bytes) -> dict[str, Any]:
    generated = "/mlx-generated/" in f"/{path}"
    ordinary = Path(path).suffix in (".swift", ".cpp") and not generated
    runtime_embedded = generated
    if path.endswith(".swift"):
        runtime_embedded = swift_contains_embedded_source(data)
    if generated:
        source_kind = "generated_runtime_embedded_source"
        exclusion = "runtime-effective generated C++ source; synchronized twin required"
    elif runtime_embedded:
        source_kind = "ordinary_compiled_source_with_runtime_embedded_text"
        exclusion = "only lexer-proven outer Swift comments may be considered"
    elif path.endswith((".metal", ".h")):
        source_kind = "runtime_effective_kernel_source"
        exclusion = "AOT/JIT/kernel twin source excluded from this plan"
    else:
        source_kind = "ordinary_compiled_source"
        exclusion = None
    return {
        "language": language_for(path),
        "generated": generated,
        "runtime_embedded": runtime_embedded,
        "ordinary_compiled_source": ordinary,
        "source_kind": source_kind,
        "generated_or_kernel_exclusion": exclusion,
    }


def prior_payload_records() -> dict[str, dict[str, Any]]:
    data = json.loads((ROOT / PRIOR_MANIFEST).read_text())
    records = {
        item["path"]: item
        for item in data["payload_reconstruction"]["common_files"]
    }
    specific = data["payload_reconstruction"]["receipt_specific_files"]
    for item in specific["e27f1ce4-23bb-4b5f-8e8e-90082be9ea3a"]:
        records[item["path"]] = item
    return records


def canonical_surface_digest(records: list[dict[str, Any]]) -> str:
    logical = [
        {"path": item["path"], "size": item["bytes"], "sha256": item["sha256"]}
        for item in records
    ]
    encoded = json.dumps(
        logical, sort_keys=True, separators=(",", ":"), ensure_ascii=False
    ).encode("utf-8") + b"\n"
    return sha256(encoded)


def validate_surface_summary(summary: dict[str, int | str]) -> None:
    expected: dict[str, int | str] = {
        "expanded_regular_files": EXPECTED_FILE_COUNT,
        "current_bytes": EXPECTED_TOTAL_BYTES,
        "current_global_headroom_bytes": EXPECTED_GLOBAL_HEADROOM,
        "target_bytes": EXPECTED_TARGET_BYTES,
        "target_headroom_bytes": EXPECTED_TARGET_HEADROOM,
        "canonical_logical_manifest_sha256": EXPECTED_CANONICAL_MANIFEST_SHA256,
    }
    for key, value in expected.items():
        if summary.get(key) != value:
            raise AuditError(f"submitted surface control mismatch: {key}")


def build_surface_manifest() -> tuple[list[dict[str, Any]], bytes, list[str]]:
    contract, contract_raw = base_contract()
    rules = contract["editablePaths"]
    base_paths = base_surface_paths(rules)
    working_paths, matched_by = working_surface_paths(rules)
    if base_paths != working_paths:
        raise AuditError("required-base and working submitted path sets differ")
    prior = prior_payload_records()
    if set(prior) != set(working_paths):
        raise AuditError("ranked-payload manifest path set differs from reconstructed surface")

    records: list[dict[str, Any]] = []
    total = 0
    for path in working_paths:
        data = (ROOT / path).read_bytes()
        size = len(data)
        digest = sha256(data)
        total += size
        prior_item = prior[path]
        if prior_item["size"] != size or prior_item["sha256"] != digest:
            raise AuditError(f"ranked-payload cross-check failed for {path}")
        record = {
            "path": path,
            "sha256": digest,
            "bytes": size,
            "per_file_limit_bytes": MAX_FILE_BYTES,
            "per_file_headroom_bytes": MAX_FILE_BYTES - size,
            "editable_path_rule": matched_by[path],
            **source_classification(path, data),
        }
        if record["per_file_headroom_bytes"] < 0:
            raise AuditError(f"per-file cap exceeded by {path}")
        records.append(record)

    target_record = next(item for item in records if item["path"] == TARGET)
    validate_surface_summary(
        {
            "expanded_regular_files": len(records),
            "current_bytes": total,
            "current_global_headroom_bytes": MAX_TOTAL_BYTES - total,
            "target_bytes": target_record["bytes"],
            "target_headroom_bytes": target_record["per_file_headroom_bytes"],
            "canonical_logical_manifest_sha256": canonical_surface_digest(records),
        }
    )
    return records, contract_raw, rules


def build_reclamation_plan() -> dict[str, Any]:
    data = (ROOT / TARGET).read_bytes()
    spans = scan_swift(data)
    code = masked_code(data, spans)
    location_tokens = [
        {
            "token": match.group().decode("ascii"),
            "byte": match.start(),
            "line": line_number(data, match.start()),
        }
        for match in SOURCE_LOCATION_PATTERN.finditer(code)
    ]
    if location_tokens:
        raise AuditError(
            "source-location-sensitive tokens make target comment deletion ambiguous"
        )
    ranges, exclusions = whole_line_comment_blocks(data, spans)
    candidate = apply_ranges(data, ranges)
    removed = [
        data[item["start_byte"] : item["end_byte_exclusive"]] for item in ranges
    ]
    reconstructed = reconstruct_original(candidate, ranges, removed, len(data))
    if reconstructed != data:
        raise AuditError("reverse reconstruction hash check failed")
    if data.count(b"\n") != candidate.count(b"\n"):
        raise AuditError("candidate changed physical line count")

    removed_bytes = sum(item["bytes"] for item in ranges)
    return {
        "paths": [TARGET],
        "path_count": 1,
        "class": "lexer_proven_swift_whole_line_comments_only",
        "ranges": ranges,
        "range_count": len(ranges),
        "excluded_comment_sites": exclusions,
        "source_location_tokens_outside_strings_and_comments": location_tokens,
        "original_bytes": len(data),
        "original_sha256": sha256(data),
        "candidate_bytes": len(candidate),
        "candidate_sha256": sha256(candidate),
        "reclaimed_bytes": removed_bytes,
        "newline_count_preserved": data.count(b"\n"),
        "nondeleted_bytes_remain_in_order": True,
        "reverse_reconstruction_matches_original": True,
        "reverse_reconstruction_sha256": sha256(reconstructed),
        "writes_submitted_files": False,
        "dry_run_medium": "in_memory_only",
    }


def synthetic_ranges(data: bytes) -> list[dict[str, Any]]:
    spans = scan_swift(data)
    code = masked_code(data, spans)
    if SOURCE_LOCATION_PATTERN.search(code):
        return []
    return whole_line_comment_blocks(data, spans)[0]


def expect_rejected(name: str, condition: bool, detail: str) -> dict[str, Any]:
    if not condition:
        raise AuditError(f"positive control failed: {name}")
    return {"name": name, "status": "PASS", "detail": detail}


def run_positive_controls(plan: dict[str, Any]) -> list[dict[str, Any]]:
    controls: list[dict[str, Any]] = []

    string_fixture = b'let a = "// ordinary"\nlet b = #"// raw"#\n'
    controls.append(
        expect_rejected(
            "comment_like_sequences_inside_swift_strings",
            synthetic_ranges(string_fixture) == [],
            "ordinary and raw string contents produced zero deletion ranges",
        )
    )

    embedded_fixture = (
        b'let source = #"""\n'
        b'// embedded Metal comment\n'
        b'kernel void active_kernel() {}\n'
        b'"""#\n'
    )
    controls.append(
        expect_rejected(
            "embedded_metal_source_range",
            synthetic_ranges(embedded_fixture) == [],
            "comment-like Metal text inside a Swift raw multiline string was excluded",
        )
    )

    license_fixture = (
        b"// Copyright 2026 Example\n"
        b"// Licensed under the Example License\n"
        b"let value = 1\n"
    )
    controls.append(
        expect_rejected(
            "required_license_block",
            synthetic_ranges(license_fixture) == [],
            "the complete adjacent license comment block was excluded",
        )
    )

    active_fixture = (
        b'let activeRegistry = ProcessInfo.processInfo.environment['
        b'"ACTIVE_SELECTOR"] != "0"\n'
        b"// removable explanation\n"
    )
    active_ranges = synthetic_ranges(active_fixture)
    token_offset = active_fixture.index(b"ACTIVE_SELECTOR")
    token_covered = any(
        item["start_byte"] <= token_offset < item["end_byte_exclusive"]
        for item in active_ranges
    )
    controls.append(
        expect_rejected(
            "active_selector_registry_token",
            len(active_ranges) == 1 and not token_covered,
            "the code token remained outside the sole comment-only deletion range",
        )
    )

    macro_fixture = b"#define VALUE \\\n// unsafe continuation site\n1\n"
    macro_comment = macro_fixture.index(b"//")
    macro_hazard = (
        b"#define" in macro_fixture
        and b"\\\n" in macro_fixture
        and macro_comment > macro_fixture.index(b"\\\n")
    )
    controls.append(
        expect_rejected(
            "c_cpp_macro_line_continuation_hazard",
            macro_hazard,
            "C/C++/Metal files are excluded; the fixture's continued macro is rejected",
        )
    )

    first = plan["ranges"][0]
    target_data = (ROOT / TARGET).read_bytes()
    corrupted = copy.deepcopy(first)
    corrupted["removed_sha256"] = "0" * 64
    hash_rejected = False
    try:
        apply_ranges(target_data, [corrupted])
    except AuditError:
        hash_rejected = True
    controls.append(
        expect_rejected(
            "corrupted_expected_byte_hash",
            hash_rejected,
            "a modified deletion receipt failed closed before dry-run application",
        )
    )

    corrupted_summary: dict[str, int | str] = {
        "expanded_regular_files": EXPECTED_FILE_COUNT + 1,
        "current_bytes": EXPECTED_TOTAL_BYTES,
        "current_global_headroom_bytes": EXPECTED_GLOBAL_HEADROOM,
        "target_bytes": EXPECTED_TARGET_BYTES,
        "target_headroom_bytes": EXPECTED_TARGET_HEADROOM,
        "canonical_logical_manifest_sha256": EXPECTED_CANONICAL_MANIFEST_SHA256,
    }
    count_rejected = False
    try:
        validate_surface_summary(corrupted_summary)
    except AuditError:
        count_rejected = True
    controls.append(
        expect_rejected(
            "corrupted_surface_manifest",
            count_rejected,
            "a changed file count failed the same exact-surface validator used by the audit",
        )
    )
    return controls


def build_manifest() -> dict[str, Any]:
    records, contract_raw, rules = build_surface_manifest()
    plan = build_reclamation_plan()
    controls = run_positive_controls(plan)
    current_total = sum(item["bytes"] for item in records)
    after_total = current_total - plan["reclaimed_bytes"]
    target_after = plan["candidate_bytes"]
    global_gate = plan["reclaimed_bytes"] >= GLOBAL_RECLAMATION_GATE
    target_gate = plan["reclaimed_bytes"] >= TARGET_RECLAMATION_GATE
    decision = "GO" if global_gate and target_gate else "NO-GO"
    return {
        "schema_version": 1,
        "audit": {
            "assignment_id": (
                "cedar-nezuko-submitted-surface-reclamation-audit-20260810"
            ),
            "revision_id": (
                "cedar-nezuko-submitted-surface-reclamation-audit-20260810-r1"
            ),
            "pull_request": 665,
            "required_base_sha": BASE_SHA,
            "audit_source_head_sha": AUDIT_SOURCE_HEAD_SHA,
            "scope": "research-only; no submitted file writes, build, or inference",
        },
        "surface": {
            "contract_path": "benchmark.json",
            "contract_sha256": sha256(contract_raw),
            "editable_path_entries": len(rules),
            "editable_paths": rules,
            "expanded_regular_files": len(records),
            "current_bytes": current_total,
            "total_limit_bytes": MAX_TOTAL_BYTES,
            "current_global_headroom_bytes": MAX_TOTAL_BYTES - current_total,
            "canonical_logical_manifest_sha256": canonical_surface_digest(records),
            "canonical_logical_manifest_encoding": (
                "UTF-8 compact JSON array sorted by path; objects contain path, size, "
                "and sha256; keys sorted; one LF appended"
            ),
            "expected_control": {
                "expanded_regular_files": EXPECTED_FILE_COUNT,
                "current_bytes": EXPECTED_TOTAL_BYTES,
                "current_global_headroom_bytes": EXPECTED_GLOBAL_HEADROOM,
                "target_bytes": EXPECTED_TARGET_BYTES,
                "target_headroom_bytes": EXPECTED_TARGET_HEADROOM,
            },
            "ranked_payload_cross_check": {
                "manifest": PRIOR_MANIFEST,
                "all_paths_sizes_and_sha256_match_e27": True,
            },
            "files": records,
        },
        "semantic_proofs": {
            "swift-comment-token-preserve-line-map-v1": {
                "selection": (
                    "only indentation plus a whole-line Swift // or /// token, "
                    "recognized outside strings and nested block comments"
                ),
                "preserved": (
                    "every newline and every nondeleted byte, in original order"
                ),
                "excluded": (
                    "inline comments, block comments, strings/raw strings, embedded "
                    "source text, license/tooling blocks, generated/kernel files, "
                    "and files with live #line/#column/#sourceLocation tokens"
                ),
                "runtime_argument": (
                    "the removed bytes are lexical trivia on lines containing no "
                    "code token; preserving newlines preserves physical line numbers"
                ),
            }
        },
        "reclamation_plan": plan,
        "dry_run_totals": {
            "before_total_bytes": current_total,
            "after_total_bytes": after_total,
            "reclaimed_bytes": plan["reclaimed_bytes"],
            "before_global_headroom_bytes": MAX_TOTAL_BYTES - current_total,
            "after_global_headroom_bytes": MAX_TOTAL_BYTES - after_total,
            "target_before_bytes": plan["original_bytes"],
            "target_after_bytes": target_after,
            "target_before_headroom_bytes": MAX_FILE_BYTES - plan["original_bytes"],
            "target_after_headroom_bytes": MAX_FILE_BYTES - target_after,
        },
        "positive_controls": controls,
        "decision": {
            "status": decision,
            "global_threshold_bytes": GLOBAL_RECLAMATION_GATE,
            "global_threshold_passed": global_gate,
            "target_threshold_bytes": TARGET_RECLAMATION_GATE,
            "target_threshold_passed": target_gate,
            "follow_up_paths": [TARGET] if decision == "GO" else [],
            "follow_up_submitted_file_count": 1 if decision == "GO" else 0,
            "latency_or_score_claim": None,
        },
    }


def verify_manifest(manifest: dict[str, Any]) -> None:
    fresh = build_manifest()
    expected_surface = manifest.get("surface", {})
    fresh_surface = fresh["surface"]
    for key in (
        "contract_sha256",
        "expanded_regular_files",
        "current_bytes",
        "current_global_headroom_bytes",
    ):
        if expected_surface.get(key) != fresh_surface[key]:
            raise AuditError(f"manifest surface verification failed at {key}")
    expected_files = expected_surface.get("files")
    if expected_files != fresh_surface["files"]:
        raise AuditError("manifest file records differ from current surface")

    plan = manifest.get("reclamation_plan", {})
    target_data = (ROOT / TARGET).read_bytes()
    candidate = apply_ranges(target_data, plan.get("ranges", []))
    removed = [
        target_data[item["start_byte"] : item["end_byte_exclusive"]]
        for item in plan.get("ranges", [])
    ]
    reconstructed = reconstruct_original(
        candidate, plan.get("ranges", []), removed, len(target_data)
    )
    if sha256(candidate) != plan.get("candidate_sha256"):
        raise AuditError("manifest candidate hash mismatch")
    if reconstructed != target_data:
        raise AuditError("manifest reverse reconstruction mismatch")
    if manifest.get("decision") != fresh["decision"]:
        raise AuditError("manifest decision differs from fresh audit")


def checked_output_path(value: str) -> Path:
    path = (ROOT / value).resolve() if not Path(value).is_absolute() else Path(value).resolve()
    if path.parent != RESEARCH_ROOT:
        raise AuditError("outputs must be direct children of research/")
    return path


def controls_text(manifest: dict[str, Any]) -> str:
    lines = ["submitted-surface reclamation positive controls"]
    lines.extend(
        f"PASS {item['name']}: {item['detail']}"
        for item in manifest["positive_controls"]
    )
    lines.append(
        "PASS submitted_files_read_only: dry run used in-memory byte strings only"
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Audit a reversible, research-only submitted-source deletion plan."
    )
    parser.add_argument("--output", help="write a manifest under research/")
    parser.add_argument(
        "--controls-output", help="write positive-control output under research/"
    )
    parser.add_argument("--verify", help="verify an existing manifest")
    args = parser.parse_args()

    try:
        if args.verify:
            path = checked_output_path(args.verify)
            manifest = json.loads(path.read_text())
            verify_manifest(manifest)
            print(
                "verified: files=142 bytes=2984121 "
                f"reclaimed={manifest['reclamation_plan']['reclaimed_bytes']} "
                f"decision={manifest['decision']['status']}"
            )
            return 0

        manifest = build_manifest()
        if args.output:
            output = checked_output_path(args.output)
            output.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
        if args.controls_output:
            controls_output = checked_output_path(args.controls_output)
            controls_output.write_text(controls_text(manifest))
        print(
            f"surface={manifest['surface']['expanded_regular_files']} "
            f"bytes={manifest['surface']['current_bytes']} "
            f"ranges={manifest['reclamation_plan']['range_count']} "
            f"reclaimed={manifest['reclamation_plan']['reclaimed_bytes']} "
            f"decision={manifest['decision']['status']}"
        )
        return 0
    except (AuditError, OSError, json.JSONDecodeError, KeyError, ValueError) as error:
        print(f"audit failed closed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
