#!/usr/bin/env bash
# R118-A: every analysis in one place, so the numbers in RESULT.md have exactly
# one provenance and can be regenerated by one command.
#
# Run this only when no timing measurement is live (HOST-HYGIENE.md).
set -u
cd "$(dirname "$0")/../.."
E=research/maple-tanjiro-r118/evidence
B="${1:-20000}"

for d in orderA orderB control; do
  echo "################################################################ ${d}"
  python3 research/maple-tanjiro-r118/analyze-dose.py "${E}/${d}" \
    --warmup 8 --boot "${B}" --label "${d}"
  echo "---------------------------------------------- confound check ${d}"
  python3 research/maple-tanjiro-r118/confound-check.py "${E}/${d}"
done

echo "################################################################ divergence cost"
if [ -d "${E}/diverg" ]; then
  python3 research/maple-tanjiro-r118/divergence-cost.py "${E}/diverg" \
    --warmup 8 --boot "${B}"
else
  echo "(no ${E}/diverg yet)"
fi

echo "################################################################ files"
ls -l "${E}"/*/summary-*.json "${E}"/*/raw-steps-*.csv 2>/dev/null
